# Generated by Django 5.1.3 on 2024-11-10 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=250)),
                ("prefers_2016_legacy_report", models.BooleanField(default=False)),
                ("is_community_college", models.BooleanField(default=True)),
                ("category", models.IntegerField(default=0)),
                ("begin_id", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionNames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("from_year", models.IntegerField(null=True)),
                ("has_departments", models.BooleanField(default=True)),
                ("hide_in_list", models.BooleanField(default=False)),
                (
                    "alternate_institution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assist.institution",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="assist.institution",
                    ),
                ),
            ],
        ),
    ]
