# Generated by Django 5.1.3 on 2024-11-09 07:29

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
            ],
            managers=[
                ('institution_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assist.institution')),
            ],
        ),
    ]
