# Generated by Django 5.1.3 on 2024-11-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='begin_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institution',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institution',
            name='is_community_college',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='prefers_2016_legacy_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institutionnames',
            name='has_departments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institutionnames',
            name='hide_in_list',
            field=models.BooleanField(default=False),
        ),
    ]
