# Generated by Django 5.1.3 on 2024-11-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assist", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InstitutionNames",
            new_name="InstitutionName",
        ),
    ]
